# Generated by Django 5.0.2 on 2024-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_myuser_is_user_myuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
