# Generated by Django 5.0.2 on 2024-03-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_myuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
